Update on 2023-11-29

diff --git a/pkglinux-pkgsrc.2022Q2/native/bootscripts/files/native/sbin/pkg-strap b/pkglinux-pkgsrc.2022Q2/native/bootscripts/files/native/sbin/pkg-strap
--- a/pkglinux-pkgsrc.2022Q2/native/bootscripts/files/native/sbin/pkg-strap
+++ b/pkglinux-pkgsrc.2022Q2/native/bootscripts/files/native/sbin/pkg-strap
@@ -84,19 +84,16 @@ shift "$(($OPTIND -1))"
 
 [ ${UID} -ne 0 ] && echo "$0 will not be performed when not running as root" && exit 1;
 
-pkg-strap-try-url () {
-#	if [[ $(curl -s --head "$1" | head -n 1 | grep "HTTP/[1-3].[0-9] [23]..") ]]; then
-#	if curl --head --silent --fail "$1" &> /dev/null; then
-	if curl --head --silent --fail "$1" 2>&1> /dev/null; then
-		echo "$1 is available."
-	else
-		echo "$1 is not available."
-		exit 1
-	fi
-}
-
 [[ "$#" -gt 0 ]] && { PKG_STRAP_REPO=$1; }
-pkg-strap-try-url $PKG_STRAP_REPO
+
+#if [[ $(curl -s --head "$PKG_STRAP_REPO" | head -n 1 | grep "HTTP/[1-3].[0-9] [23]..") ]]; then
+#if curl --head --silent --fail "$PKG_STRAP_REPO" &> /dev/null; then
+if curl --head --silent --fail "$PKG_STRAP_REPO" 2>&1> /dev/null; then
+	echo "$PKG_STRAP_REPO is available."
+else
+	echo "$PKG_STRAP_REPO is not available."
+	exit 1
+fi
 
 pkg_add $PKG_STRAP_VERBOSE -K /$PKG_STRAP_PREFIX/pkgdb $PKG_STRAP_REPO/pkg_install
 
